version: "3.9"

services:
    web:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
    php-fpm:
        # image: php:8-fpm
        volumes:
          - ./src:/var/www/html
        build:
          context: .
          dockerfile: Dockerfile
    composer:
        image: "composer"
        volumes:
            - "./app:/app"
        command: install
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example

    adminer:
      image: adminer
      restart: always
      ports:
        - 8081:8080